### ISSUE TITLE
Discrepancies between instructions and required JRE version

### ISSUE THREAD

**Issue by aryoadhi** [dudehacker/Magic-Copy#10]
Some users reported that they cannot run the program using provided instructions, due to the difference between JRE version provided in the instructions and what the JAR file required.

I used Java version 21 and the program runs fine. The program may run on earlier Java, but I'm unsure which version. Is it able to run on latest Java 8?

```
$> java -version
openjdk version "21.0.1" 2023-10-17 LTS
OpenJDK Runtime Environment Zulu21.30+15-CA (build 21.0.1+12-LTS)
OpenJDK 64-Bit Server VM Zulu21.30+15-CA (build 21.0.1+12-LTS, mixed mode, sharing)
```

**Comment by dudehacker** [comment]
fixed instruction

latest version need java 21 but old version uses java 8
