### ISSUE TITLE
.ogg files being soft-hitnormal in storyboard

### ISSUE THREAD

**Issue by FAMossu** [dudehacker/Magic-Copy#2]
Recently, I got issue turning after copied, i'm using .ogg files from BMS
the .ogg turning into soft-hitnormal in storyboard after copied
sorry i can't provides the screenshot because i fixed it fast by renames the extension to .wav 

the map itself is this https://osu.ppy.sh/s/1071024
if you want to do the experiment with it, turn them back to .ogg

**Comment by dudehacker** [comment]
When adding note manually to SB, user picks the filename from a list of files present in song folder

When copying note to SB with program, I don't know whether your hitobject with default hs is using wav or ogg

For example: this is a hitobject with W+C
160,192,67469,1,6,0:0:0:0:

I can't tell whether I need create soft-hitwhistle.wav or soft-hitwhistle.ogg in SB.

So the work-around is to rename all ogg to wav before using magic copy

**Comment by FAMossu** [comment]
if you were looking how converting .ogg to .wav, check this out

First, you must know where your partition where osu client located, it's in `C:` or `D:` or `E:` or wherever.
Then, open command prompt (cmd).
Located the your partition where osu client located, (example `E:`), then type `E:`
Next, if `C:` default cmd changed to `E:`, then open your osu folder name, example: `cd game/osu`, make sure has `cd` (create directory) because it's a syntax to open directories.
Next, write this to change the extension from .ogg to .wav,
`ren *.ogg *.wav`
`ren *.current_extension *.wish_extension`
Finished.

**Comment by mcendu** [comment]
So this is a "won't fix" issue?

**Comment by dudehacker** [comment]
the only use case for this: when u have a keysound map and wav exceeds file upload limit, therefore u must use all ogg for your keysounds.

this is so rare that its not worth my time to fix it. the workaround to convert everything to wav is much easier.

**Comment by dudehacker** [comment]
if anyone wants to fix it, pls go ahead and make a pull request
